sudo: required
services:
  - docker

before_install:
  - docker build -t vasiltehanov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vasiltehanov/react-test npm test -- --coverage

after_success:
  - docker build -t vasiltehanov/multi-client ./client
  - docker build -t vasiltehanov/multi-nginx ./nginx
  - docker build -t vasiltehanov/multi-server ./server
  - docker build -t vasiltehanov/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push vasiltehanov/multi-client
  - docker push vasiltehanov/multi-nginx
  - docker push vasiltehanov/multi-server
  - docker push vasiltehanov/multi-worker
